ad_manager/urls.py
# Copyright 2016 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# External packages
from django.conf.urls import patterns, url

# SCION-WEB
from ad_manager import views

api_patterns_internal = patterns(
    '',
    url(r'^api/v1/internal/isd/(?P<isd_id>\d+)/as/(?P<as_id>\d+)/topo_hash/?$',
        views.as_topo_hash, name='topo_hash'),
    url(r'^api/v1/internal/update_coord_settings/?$',
        views.coord_service_update, name='coord_service_update'),
    url(r'^api/v1/internal/join_requests/isd-as/(?P<isd_as>\d+-\d+)'
        '/request/(?P<request_id>\d+)/?$',
        views.join_request_action, name='join_request_action'),
    url(r'^api/v1/internal/.*$',
        views.wrong_api_call, name='wrong_api_call'),
)

api_patterns_external = patterns(
    # unimplemented API calls get treated as wrong API calls
    '',
    url(r'^api/v1/services_status/?$',
        views.wrong_api_call, name='services_status'),
    url(r'^api/v1/open_policy/?$',
        views.wrong_api_call, name='open_policy'),
    url(r'^api/v1/receive_notification/?$',
        views.wrong_api_call, name='receive_notification'),
    url(r'^api/v1/peering_request/?$',
        views.wrong_api_call, name='peering_request'),
    url(r'^api/v1/.*$',
        views.wrong_api_call, name='wrong_api_call'),  # Default route
)

isd_patterns = patterns(
    '',
    url(r'^isds/?$',
        views.ISDListView.as_view(), name='list_isds'),
    url(r'^isds/upload_file/?$',
        views.upload_file, name='upload_file_ref'),
    url(r'^isds/add_isd/?$',
        views.add_isd, name='add_isd'),
    url(r'^isds/join_isd/?$',
        views.request_join_isd, name='join_isd'),
    url(r'^isds/poll_join_reply/?$',
        views.poll_join_reply, name='poll_join_reply'),
    url(r'^isds/save_all_topologies/?$',
        views.save_all_topologies, name='save_all_topologies'),
    url(r'^isds/(?P<pk>\d+)/?$',
        views.ISDDetailView.as_view(), name='isd_detail'),
)

ad_patterns = patterns(
    '',
    url(r'^ads/(?P<as_id>\d+)/?$',
        views.ADDetailView.as_view(), name='ad_detail'),
    url(r'^ads/(?P<as_id>\d+)/#!topology/?$',
        views.ADDetailView.as_view(), name='ad_detail_topology'),
    url(r'^ads/(?P<as_id>\d+)/#!topology&expanded_routers/?$',
        views.ADDetailView.as_view(), name='ad_detail_topology_routers'),
    url(r'^ads/(?P<as_id>\d+)/#!updates/?$',
        views.ADDetailView.as_view(), name='ad_detail_updates'),
    url(r'^ads/(?P<as_id>\d+)/#!requests/?$',
        views.ADDetailView.as_view(), name='ad_connection_requests'),
    url(r'^ads/generate_topology/?$',
        views.generate_topology, name='generate_topology'),
    url(r'^ads/add_to_topology/?$',
        views.add_to_topology, name='add_to_topology'),
    url(r'^ads/isd/(?P<isd_id>\d+)/as/(?P<as_id>\d+)/simple_configuration/?$',
        views.simple_configuration, name='simple_configuration'),
)

connection_request_patterns = patterns(
    '',
    url(r'^connection_requests/new/(?P<as_id>\d+)/?$',
        views.ConnectionRequestView.as_view(), name='new_connection_request'),
    url(r'^connection_requests/(?P<con_req_id>\d+)/action/?$',
        views.connection_request_action, name='connection_request_action'),
)

misc = patterns(
    '',
    url(r'^network/?$',
        views.network_view, name='network_view'),
    url(r'^network/isd/(?P<isd_id>\d+)/as/(?P<as_id>\d+)/?$',
        views.network_view_neighbors, name='network_view_as'),
    url(r'^coord_service/?$',
        views.coord_service, name='coord_service'),
)

urlpatterns = api_patterns_internal + isd_patterns + ad_patterns + \
              connection_request_patterns + misc

web_scion/urls.py
# Copyright 2016 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# External packages
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect

# SCION
from ad_manager.admin import admin_site


# Basic URLs
urlpatterns = patterns(
    '',
    url(r'^$', lambda _: HttpResponseRedirect(reverse('list_isds'))),
    url(r'^admin/', include(admin_site.urls)),
    url(r'^as_manager/', include('ad_manager.urls')),
)

# Logout
urlpatterns += patterns(
    '',
    url(r'^logout/$', logout,
        {'template_name': 'registration/logged_out.html'}, name='logout'),
)


if settings.ENABLED_2FA:
    # 2FA with Twilio
    from two_factor.urls import urlpatterns as tf_urls
    from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls

    urlpatterns += patterns(
        '',
        url(r'', include(tf_urls + tf_twilio_urls, 'two_factor')),
    )
    settings.LOGIN_URL = reverse_lazy('two_factor:login')

else:
    # Basic login/logout views
    urlpatterns += patterns(
        '',
        url(r'^login/$', login,
            {'template_name': 'admin/login.html'}, name='login'),
    )
    settings.LOGIN_URL = reverse_lazy('login')

ad_manager/forms.py
# Copyright 2016 ETH Zurich
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# External packages
from django import forms
from django.shortcuts import get_object_or_404

# SCION
from lib.types import LinkType

# SCION-WEB
from ad_manager.models import (
    AD,
    ConnectionRequest,
    OrganisationAdmin,
)


# never use for untrusted uploads
class UploadFileForm(forms.Form):
    file = forms.FileField()
    # filename = forms.CharField(max_length=25)  # additional field to rename f


class CoordinationServiceSettingsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        try:
            coord_settings = OrganisationAdmin.objects.get(user_id=user_id)
        except OrganisationAdmin.DoesNotExist:
            coord_settings = OrganisationAdmin()
            coord_settings.account_id = 'Not set'
            coord_settings.secret = 'Not set'

        self.fields['account_id'] = forms.CharField(widget=forms.TextInput(
            attrs={'class': 'input-field-coord-account_id',
                   'value': coord_settings.account_id})
        )
        self.fields['secret'] = forms.CharField(widget=forms.TextInput(
            attrs={'class': 'input-field-coord-secret',
                   'value': coord_settings.secret})
        )

    class Meta:
        model = OrganisationAdmin
        fields = ('account_id', 'secret')
        labels = {'AccountId': 'Secret'}


class ConnectionRequestForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        current_as_id = kwargs.pop('pk')
        super(ConnectionRequestForm, self).__init__(*args, **kwargs)

        ad = get_object_or_404(AD, as_id=current_as_id)
        router_choices = []

        self.fields['connect_from'] = forms.CharField(
            widget=forms.HiddenInput(attrs={'value': current_as_id})
        )
        self.fields['connect_to'] = forms.CharField(
            widget=forms.TextInput(attrs={'placeholder':
                                          'ISD-AS to connect to'})
        )
        # populate the choice field with options to choose from
        for router in ad.borderrouter_set.all():
            for router_addr in router.borderrouteraddress_set.all():
                if router_addr.is_public:
                    for router_intf in router_addr.borderrouterinterface_set.all():
                        val = router_intf.addr
                        if router_intf.l4port:  # UdpToPort is not empty
                            val += ":" + str(router_intf.l4port)
                        router_choices.append((val, val))

        self.fields['router_info'] = forms.ChoiceField(
            choices=router_choices
        )

    class Meta:
        model = ConnectionRequest
        fields = ('connect_to', 'router_info', 'overlay_type', 'mtu',
                  'bandwidth', 'link_type', 'info')
        labels = {'connect_to': 'Connect to',
                  'router_info': 'Border router information',
                  'overlay_type': 'Overlay type',
                  'mtu': 'MTU',
                  'link_type': 'Link type'}


class NewLinkForm(forms.Form):
    link_types = [LinkType.PARENT, LinkType.CHILD,
                  LinkType.PEER, LinkType.CORE]

    end_point = forms.ModelChoiceField(
        queryset=AD.objects.none(),
        widget=forms.TextInput(attrs={'placeholder': 'AD id, for example, 20'})
    )
    link_type = forms.ChoiceField(choices=zip(link_types, link_types))

    def __init__(self, *args, **kwargs):
        self.from_ad = kwargs.pop('from_ad')
        assert isinstance(self.from_ad, AD)
        end_point_field = self.base_fields['end_point']
        end_point_field.queryset = AD.objects.exclude(as_id=self.from_ad.as_id,
                                                      isd=self.from_ad.isd)
        super().__init__(*args, **kwargs)

ad_manager/templates/ad_manager/ad_detail.html
<!--
 * Copyright 2017 ETH Zurich
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

{% extends "ad_manager/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block js %}
  {{ block.super }}
    <script src="{% static 'js/ad_detail.js' %}" xmlns="http://www.w3.org/1999/html"></script>
    <script src="{% static 'js/topology_input.js' %}" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}

{% block content %}
  {% include 'ad_manager/partials/object_path.html' %}

  <h4 id="core-label" class="as-label">
    Core AS:
    {{ object.is_core_ad|yesno:"Yes,No,???" }}
    <span class="glyphicon glyphicon-{{ object.is_core_ad|yesno:"ok,remove," }}"></span>
  </h4>
  <br />

  <div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#servers" aria-controls="servers" role="tab" data-toggle="tab">AS Summary</a></li>
      <li role="presentation"><a href="#simplemode" aria-controls="simplemode" role="tab" data-toggle="tab">Simple AS Configuration</a></li>
      <li role="presentation"><a href="#topology" aria-controls="topology" role="tab" data-toggle="tab">Advanced AS Configuration</a></li>
      <li role="presentation"><a href="#requests_from_own" aria-controls="requests_from_own" role="tab" data-toggle="tab">Requests from My AS</a></li>
      <li role="presentation"><a href="#requests_from_others" aria-controls="requests_from_others" role="tab" data-toggle="tab">Requests from Other ASes</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">

      <!-- Server summary tab -->
      <div role="tabpanel" class="tab-pane active" id="servers">

        {% with table_name='Beacon servers' type="bs" servers=services addrs=service_addrs table_id='beacon-servers' %}
          {% include 'ad_manager/partials/server_table.html' %}
        {% endwith %}

        {% with table_name='Certificate servers' type="cs" servers=services addrs=service_addrs table_id='certificate-servers' %}
          {% include 'ad_manager/partials/server_table.html' %}
        {% endwith %}

        {% with table_name='Path servers' type="ps" servers=services addrs=service_addrs table_id='path-servers' %}
          {% include 'ad_manager/partials/server_table.html' %}
        {% endwith %}

        {% include 'ad_manager/partials/router_table.html' %}
        <br /><br />
      </div>

      <!-- Simple Configuration tab -->
      <div role="tabpanel" class="tab-pane" id="simplemode">
        {% with ad=object %}
          {% include 'ad_manager/partials/simple_configuration.html' %}
        {% endwith %}
      </div>

      <!-- Define Topology tab -->
      <div role="tabpanel" class="tab-pane" id="topology">
          <br />
          {% include 'ad_manager/partials/topology_input.html' %}
      </div>

      <!-- Requests from Own AS tab -->
      <div role="tabpanel" class="tab-pane" id="requests_from_own">
        {% with ad=object %}
          {% include 'ad_manager/partials/requests_from_own_as.html' %}
        {% endwith %}
      </div>

      <!-- Requests from Other ASes tab -->
      <div role="tabpanel" class="tab-pane" id="requests_from_others">
        {% with ad=object %}
          {% include 'ad_manager/partials/requests_from_other_ases.html' %}
        {% endwith %}
      </div>

    </div>
  </div>

  <br />
  <br />
  <br />
  <br />

  {% include 'ad_manager/partials/log_modal.html' %}

  <!-- JS variables passed from the view to JavaScript files -->
  <script>
    var isdAdId = '{{ object }}';
    var adDetailUrl = '';
    var adCompareUrl = '';

    // display tooltip in form
    $(function () {
          $("[data-toggle='tooltip']").tooltip();
    });

    // Update the deploy form when management interface ip gets manually set
    $('#inputManagementInterfaceIP').bind('keypress keyup blur', function() {
        $('#inputManagementInterfaceIPretrieving').val($(this).val());
    });

    // Run the core check when the value changes
    $('#inputIsCore.shownCheckbox').change(function(e) {
        checkShowCoreOption();
    });
    // Hide the link type CORE when current AS is not Core (isCore is not selected)
    function checkShowCoreOption() {
        var isChecked = $('#inputIsCore.shownCheckbox').is(':checked');
        // we need to check if CORE option already exists
        var noExistingCoreOption = $("#inputInterfaceType").find("option[value='CORE']").length == 0;
        if (isChecked && noExistingCoreOption) {
            $('#inputInterfaceType').append('<option value="CORE">CORE</option>');
        } else if (!isChecked && !noExistingCoreOption) {
            $('#inputInterfaceType').find('option[value="CORE"]').remove();
        }
    }
    // Run it always when the page is loaded (for initial value unchecked)
    checkShowCoreOption();


    // Input check the port to be in range 0 to 65535
    $('.inputPort').bind('keypress keyup blur', function(e) {
        var port = this.value;
        if (port < 0 || port > Math.pow(2,16)-1) {
            var errorColor = 'pink';
            $(this).attr('style', 'background: '+errorColor+';');
        } else {
            $(this).attr('style', '');
        }
    });

  </script>

  <!-- set data reloaded from DB -->
  <script>
    reloadedTopology = '{{ reloaded_topology }}';
    reloadedTopology = parseTopology(reloadedTopology);
    setLoadedTopology(reloadedTopology);
  </script>

  <!-- set topology hash at load time -->
  <script>
    reloadedTopologyHash = '{{ reloaded_topology_hash }}';
  </script>

  <style>
    .doc-hr {
        width: 100%;
        height: 1px;
        background: #aaaaaa;
        margin: 15px;
    }

    input {
        margin-bottom:1em;
    }
  </style>
{% endblock %}

ad_manager/templates/ad_manager/base.html
<!--
 * Copyright 2017 ETH Zurich
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <title>AS manager</title>

    <!-- Stylesheets -->
    {% block css %}
      <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
      <link rel="stylesheet" href="{% static "css/base-styles.css" %}">
      <link rel="stylesheet" href="{% static "css/bootstrap-select.min.css" %}" />
    {% endblock css %}

    <!-- Scripts -->
    {%  block js %}
      <script src="{% static "js/jquery-2.1.3.min.js" %}"></script>
      <script src="{% static "js/bootstrap.min.js" %}"></script>
      <script src="{% static "js/bootstrap-select.min.js" %}" ></script>
    {%  endblock %}
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'list_isds' %}">SCION AS manager</a>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'list_isds' %}">Home</a></li>
            <li><a href="{% url 'coord_service' %}">Coordination service</a></li>
            <li><a href="{% url 'network_view' %}">Network graph</a></li>
          </ul>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <p class="navbar-text">
                  {% if user.is_authenticated %}
                    Logged in as: <i>{{ user }}</i> (<a href="{{ logout_url }}?next={{ request.path }}">logout</a>)
                    {% if user.is_staff %}
                      || <a href="{% url 'admin:index' %}">Admin panel</a>
                    {% endif %}
                  {% else %}
                    <a href="{{ login_url }}?next={{ request.path }}">Login </a>
                  {% endif %}
                </p>
              </li>
            </ul>

        </div>
      </div>
    </nav>

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <div class="container">

      <div class="starter-template">
        {% block content %}{% endblock %}
      </div>
    </div>
    <br />
  </body>
</html>

ad_manager/templates/ad_manager/coord_service.html
{% extends "ad_manager/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h2>Showing settings for user <i>{{ user.username }}</i></h2>
  <br />
  <br />
  <br />
  <form action="{% url 'coord_service_update' %}" method="POST">
    {% csrf_token %}
    <div class="form-horizontal">
        {% bootstrap_form settings_form layout='horizontal' %}
        <input class="btn btn-info submit-settings" type="submit" value="Update settings" />
    </div>
  </form>

  <style>
    .input-field-coord-account_id {
        width: 25em;
    }
    .input-field-coord-secret {
        width: 40em;
    }
    .form-group {
        float: left;
    }
    .submit-settings {
        margin-left: 4em;
    }
  </style>
{% endblock %}

ad_manager/templates/ad_manager/isd_detail.html
<!--
 * Copyright 2017 ETH Zurich
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

{% extends "ad_manager/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <h1>
    <a href="{% url 'list_isds' %}" class="glyphicon glyphicon-home"></a>
    <span class="glyphicon glyphicon-menu-right"></span>
    ISD {{ object.id }}
  </h1>
  <hr>

  <p>
    Total number of ASes: {{ paginator.count }}
  </p>
  <ul>
    {% for ad in object_list %}
      <li>
        <a href="{% url 'ad_detail' ad.as_id %}">AS {{ ad.isd.id }}-{{ ad.as_id_str }}</a>
        {% if ad.is_core_ad %} <span class="badge alert-warning">core</span> {% endif %}
      </li>
    {% empty %}
      <li>No ASes.</li>
    {% endfor %}
  </ul>

  <div class="disp-inline-block">
      <form id="createASByFile" method="POST" enctype="multipart/form-data" action="{% url 'upload_file_ref' %}" class="disp-inline-block topofile-form">
        {% csrf_token %}
        <div class="hidden" id="topoInitUpload">
            {% bootstrap_form upload_form %}
        </div>
        <input type="test" class="hidden" name="_upload_init_topo" value="_upload_init_topo">
        <button type="button" class="btn btn-default click-confirm" id="upload-topo-btn" onclick="delayedUpload('#topoInitUpload', 'createASByFile')">
              Create AS from file
        </button>
      </form>

      <form method="POST" action="/as_manager/isds/save_all_topologies">
        {% csrf_token %}
        <input type="hidden" name="ISD" value="{{object.id}}">
        <div class="form-group">
            <br/>
            <button type="submit" class="btn">Save All Topologies</button>
        </div>
      </form>
  </div>

  <br/>
  <br/>

  <script>
    function delayedUpload(uploadInput, id) {
        $(uploadInput).find('#id_file').attr('multiple', 'multiple');
        $(uploadInput).find('#id_file').click();
        $(uploadInput).find('#id_file').change(function (){
            document.getElementById(id).submit();
        });
    }

    function setRequestIDnSubmit() {
        try {
            // set inputRequestID to the request matching the selected AS id
            var request_id = $('#new_as_id_field').find('option[value='+ $('#inputASname').val() +']').attr('request_id')
            $('#inputRequestID').val(request_id);
        } catch (e) {} // no valid match, handle as manually set
        document.getElementById('createASByID').submit();
    }
  </script>

  {% include 'ad_manager/partials/pagination_footer.html' %}

{% endblock %}

ad_manager/templates/ad_manager/isd_list.html
<!--
 * Copyright 2017 ETH Zurich
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
-->

{% extends "ad_manager/base.html" %}

{% block content %}
  <h1>
    <a href="{% url 'list_isds' %}" class="glyphicon glyphicon-home"></a>
    <span class="glyphicon glyphicon-menu-right"></span>
    All ISDs
  </h1>
  <hr>
  <ul>
    {% for isd in object_list %}
      <li><a href="{% url 'isd_detail' isd %}">ISD {{ isd }}</a></li>
    {% empty %}
      <li>No ISDs.</li>
    {% endfor %}
  </ul>

  <form method="POST" id="joinISD" action="/as_manager/isds/join_isd">
    {% csrf_token %}
    <div class="form-group">
        <br/>
        <label class="control-label" class="floor-align-text" for="inputISDToJoin">Create new AS in ISD:</label>
        <input id="inputISDToJoin" name="inputISDToJoin" type="text">
        <label class="control-label" class="floor-align-text" for="inputJoinAsACore">Join as a Core AS:</label>
        <select id="inputJoinAsACore" name="inputJoinAsACore" required>
            <option value="False" selected>False</option>
            <option value="True">True</option>
        </select>
        <button type="button" class="btn" onclick="queryForAsId();">Join</button>
    </div>
  </form>

  <!--TODO(ercanucan): This form will eventually be removed from scion-web-->
  <form method="POST" action="/as_manager/isds/add_isd">
    {% csrf_token %}
    <div class="form-group">
        <br/>
        <label class="control-label" class="floor-align-text" for="inputISDname">new ISD name:</label>
        <input id="inputISDname" name="inputISDname" type="text">
        <button type="submit" class="btn">Create ISD</button>
    </div>
  </form>

  <form method="POST" action="/as_manager/isds/poll_join_reply">
    {% csrf_token %}
    <div class="form-group">
        <br/>
        <button type="submit" class="btn">Fetch Join Replies</button>
    </div>
  </form>

  <form method="POST" action="/as_manager/isds/save_all_topologies">
    {% csrf_token %}
    {% for isd in object_list %}
      <input type="hidden" name="ISD" value="{{isd}}">
    {% endfor %}
    <div class="form-group">
        <br/>
        <button type="submit" class="btn">Save All Topologies</button>
    </div>
  </form>

  <script>
    function queryForAsId() {
        $.ajaxSetup({
            headers:
            { 'X-CSRFToken': $("input[name='csrfmiddlewaretoken']").val() }
        });
        document.getElementById('joinISD').submit();
    }
  </script>

  {% include 'ad_manager/partials/pagination_footer.html' %}
{% endblock %}

ad_manager/templates/ad_manager/new_connection_request.html
{% extends "ad_manager/base.html" %}
{% load bootstrap3 %}

{% block content %}
  <br />
  <h2>Create a new connection request</h2>
  <hr />

  <b>Connecting from:</b> <a href="{{ ad.get_absolute_url }}">AS {{ ad }}</a>
  <br />
  <br />

  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="Send Request" />
  </form>

{% endblock %}

ad_manager/templates/ad_manager/new_link.html
{% extends "ad_manager/base.html" %}
{% load bootstrap3 %}

{% block content %}
  {% with object=ad %}
    {% include 'ad_manager/partials/object_path.html' %}
  {% endwith %}

  <h2>Create a new link</h2>
  <br />
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-info" type="submit" value="Create link" />
  </form>
{% endblock %}